# Dependencies
markdown:         kramdown
highlighter:      rouge

remote_theme: fongandrew/hydeout

# Setup
title:            Hydeout
tagline:          'A Jekyll theme'
description:      'The refreshed test page.'
url:              https://030jmk.github.io
baseurl:          '/'

author:
  name:           'Jan Kopankiewicz'
  url:            https://twitter.com/JanKopankiewicz

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true

plugins:
  - jekyll-remote-theme
