# Site settings
title: 'Jan Kopankiewicz'
description: ''
url: 'jan.kopankiewicz.de'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

remote_theme: matthiaslischka/jekyll-uno

author:
  name: 'Jan Kopankiewicz'
  #email: 
  twitter_username: JanKopankiewicz
  instagram_username: 030jk
  #facebook_username: 
  #github_username: 030jmk
  linkedin_username: kopankiewicz 

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']
